-- INSERT INTO
--     dolgozo(id, vezNev, kerNev, telefon, jelszo, role, szerzodes)
-- VALUES
--     (1, 'Kis', 'Sandor', '06302583694', 'asdf1234', 'ROLE_DOLGOZO', );
--
-- INSERT INTO
--     dolgozo(id, vezNev, kerNev, telefon, jelszo, role, szerzodes)
-- VALUES
--     (2, 'Nagy', 'Géza', '06304757494', 'asdf1234', 'ROLE_DOLGOZO', );
--
-- INSERT INTO
--     dijcsomag(id, nev, havidij)
-- VALUES
--     (1, 'Praktikum', 2500);
--
-- INSERT INTO
--     dijcsomag(id, nev, havidij)
-- VALUES
--     (2, 'Borsozo+', 5000);
--
-- INSERT INTO
--     poszt(id, nev, szoveg)
-- VALUES
--     (1, 'sarga', '#A sarga az uj nem sarga!');
--
-- INSERT INTO
--     poszt(id, nev, szoveg)
-- VALUES
--     (2, 'kek', '#A kek az uj nem kek!');
--
-- INSERT INTO
--     szerzodes(id, ugyfel, dolgozo, dijcsomag, lejarat)
-- VALUES
--     (1, 1, 1, 1, 2020);
--
-- INSERT INTO
--     szerzodes(id, ugyfel, dolgozo, dijcsomag, lejarat)
-- VALUES
--     (2, 2, 2, 2, 2022);
--
-- INSERT INTO
--    ugyfel(id, vezNev, kerNev, email, dolgozo, szerzodes, jelszo, role)
-- VALUES
--     (1, 'Toth', 'Karcsi', 'tothkarcsi@asdf.com', 1, 1, 'asdf1234', 'ROLE_UGYFEL');
--
-- INSERT INTO
--    ugyfel(id, vezNev, kerNev, email, dolgozo, szerzodes, jelszo, role)
-- VALUES
--     (1, 'Nagy', 'Jakab', 'nagyjakab@asdf.com', 2, 2, 'asdf1234', 'ROLE_UGYFEL');